print("learning to move the file object ")
fileobject=open("textfile.txt","r+")
str=fileobject.read()
print(str)
print("initially,the position of the file object is:"fileobject.tell())
fileobject.seek(0)
print("now the object is at the beginning of the file:",fileobject.tell())
fileobject.seek(10)
print("we are moving to 10th byte position from the beginning of the file:")
print("the position of the file object is at",fileobject.tell())
str=fileobject.read()
print(str)